name: Build and Upload Lambdas

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:



jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Package Lambdas
        run: |
          mkdir -p dist
          for lambda in lambdas/*; do
            name=$(basename $lambda)
            echo "📦 Packaging $name"
            cp -r node_modules "$lambda/"
            cd "$lambda"
            zip -r "../../dist/$name.zip" *
            cd - > /dev/null
            rm -rf "$lambda/node_modules"
          done

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload All Lambdas to S3 🚀
        run: |
          aws s3 sync ./dist/ s3://lambda-code-tc3-g38/ \
            --exclude "*" \
            --include "*.zip" 
          echo "✅ All zip files uploaded to s3://lambda-code-tc3-g38/"


      - name: Update Lambda Function Code
        run: |
          aws lambda update-function-code \
            --function-name auth-user-function \
            --s3-bucket lambda-code-tc3-g38 \
            --s3-key auth-user.zip \
            --publish
            
          aws lambda update-function-code \
            --function-name create-user-function \
            --s3-bucket lambda-code-tc3-g38 \
            --s3-key create-user.zip \
            --publish
          
          aws lambda update-function-code \
            --function-name middleware-function \
            --s3-bucket lambda-code-tc3-g38 \
            --s3-key middleware.zip \
            --publish




